-keepclassmembers class com.medsolution.admin.data.model.** { *; }
-keep class com.google.gson.** { *; }
-keepattributes Signature
-keepattributes *Annotation*
-keep class com.medsolution.admin.di.** { *; }
